apiVersion: v1
kind: Service
metadata:
  name: doc-ingest-service
  labels:
    app: doc-ingest-service
spec:
  selector:
    app: doc-ingest-service
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP
